[package]
name = "reseau"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
bincode = "1.3"
serde_derive = "1.0"
prettytable-rs = "0.10.0"

[dev-dependencies]